### PR TITLE
Fix favicon location

### PR DESCRIPTION
**Pull request by jirikolarik**
Consider publicPath in `favicon.ico` location

Resolves https://github.com/ampedandwired/html-webpack-plugin/issues/208

### CODE REVIEW

**Comment by jantimon** [comment]
Does this also work if you specify the pats `/some` with out the trailing slash?

**Comment by jirikolarik** [comment]
It doesn't. I think that we should have absolute url for favicon if publicPath is not specified. I can add these two updates in another PR

**Comment by jantimon** [comment]
Why should it be absolute? this would destroy the backwards compatibility

**Comment by jirikolarik** [comment]
Because current implementation is wrong. Favicon, same as assets (js, css) should be still on the same location and not relative

**Pull request closed without merging**
