### PR TITLE
Allow webpack 2 rc

### PR DESCRIPTION
**Pull request by SimenB**

### CODE REVIEW

**Comment by graingert** [comment]
@jantimon do you know when this will get a release?

**Comment by jantimon** [comment]
@graingert I hope I'll find some time in the next days :)

**Comment by mrsufgi** [comment]
waiting! Thanks

**Comment by Tibfib** [comment]
Would love to see this released soon, if possible. Thanks for your work!

**Comment by jantimon** [comment]
Released.

**Pull request merged**
