### PR TITLE
add peerDeps, fix Cannot find module

### PR DESCRIPTION
**Pull request by jaredleechn**
`Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'`

### CODE REVIEW

**Comment by jantimon** [comment]
Hmm could you change the peerDependency version to `*`? 
Or do you think this might cause unintended issues?

**Comment by jaredleechn** [comment]
> Or do you think this might cause unintended issues?

yep, the major version maybe including some break changes, so I think keep `1.x` is better

**Comment by jantimon** [comment]
But we have also support for webpack 2

**Comment by jaredleechn** [comment]
how about `>= 1.12.0 < 3`

**Pull request closed without merging**
