### PR TITLE
Refactor lot of things.

### PR DESCRIPTION
**Pull request by izaakschroeder**
* 100% code coverage with `instanbul`,
 * Continuous integration with `travisci`,
 * Support for common chunks (https://github.com/ampedandwired/html-webpack-plugin/issues/4),
 * Support for externals,
 * Use more standard underscore/lo-dash templates,
 * More aggressive lint checking with `eslint`,
 * EditorConfig support,
 * Updated code documentation,
 * Automatic `publicPath` support (https://github.com/ampedandwired/html-webpack-plugin/issues/9),
 * Updated README.

This is obviously API incompatible, so in the spirit of cleanliness the template parameters and options have been cleaned up too. Version bump included for good measure.

Could still use some work. Pretty much all the existing tests pass with very minimal changes, if any.

### CODE REVIEW

**Comment by ampedandwired** [comment]
Wow, awesome stuff. Thanks for taking the time to do this and submit a PR. There are a lot of changes here, basically a complete rewrite. Nothing wrong with that per-se, although I'd probably have preferred bringing in the changes incrementally. I'll review the changes anyway and see how to best bring it all in.

**Comment by izaakschroeder** [comment]
:tada: sounds good to me!

**Comment by jantimon** [comment]
:+1:

**Comment by izaakschroeder** [comment]
Waiting to :ship: this @ampedandwired :tada:

**Comment by ampedandwired** [comment]
I must apologise, I have had some personal issues of late that have taken priority, and as a consequence this project hasn't gotten the attention it deserves. Things are settling down now, and I will endeavour to get things going again this week.

**Comment by izaakschroeder** [comment]
I can maintain this if you'd rather @ampedandwired

**Comment by ampedandwired** [comment]
Thanks @izaakschroeder, I could use some help with this. I'm getting through some of the backlog now, will ping you offline.

**Comment by izaakschroeder** [comment]
https://github.com/ampedandwired/html-webpack-plugin/pull/14 is pretty much incompatible with this.

**Pull request closed without merging**
