### PR TITLE
fix include template

### PR DESCRIPTION
**Pull request by lalop**
add server-side loader method https://github.com/blueimp/JavaScript-Templates#server-side

### CODE REVIEW

**Comment by jantimon** [comment]
Please rebase and rename the variable.

**Comment by jantimon** [comment]
Hey @lalop thx for your work - sorry for the delay.
I'll try to merge this soon

**Comment by dwayne** [comment]
@jantimon When will this be merged? I would really :heart: to have this fixed.

**Comment by jantimon** [comment]
Could you please merge all your changes in one commit with a meaning full message so I can publish 1.8.0?

**Comment by jantimon** [comment]
Please note that 2.x already includes this feature

**Comment by dwayne** [comment]
@jantimon I did not know 2.x already had the feature. Thanks for letting me know. :+1:

**Pull request closed without merging**
