### PR TITLE
Fix template path resolving regexp to support loader query parameters

### PR DESCRIPTION
**Pull request by PeachScript**
More details in this issue: #541

### CODE REVIEW

**Comment by jantimon** [comment]
Could you tell a little bit more about the changed regexp?

**Comment by PeachScript** [comment]
Of course, I have described the problem in the issue #541 .

**Comment by jantimon** [comment]
Can you please also explain the solution?

**Comment by PeachScript** [comment]
Before change, the regular expression /([!])([^/\\][^!?]+|[^/\\!?])($|\?.+$)/ will match the following substrings in `!!html!swig?raw=true!./src/tmpl/index.html`:
1. `!` - prefix
2. `swig` - filepath
3. `?raw=true!./src/tmpl/index.html` - postfix

And the `getFullTemplatePath` function will return the error full template path `!!html!/Absolute/path/to/context/swig?raw=true!./src/tmpl/index.swig`, because of the regular expression ignore the remaining string if it read a `?`, and the substring `swig` be treated as a file path, the real file path be treated as a part of the postfix.

After change, the regular expression /([!])([^/\\][^!?]+|[^/\\!?])($|\?**[^!?\n]**+$)/ (Only need to look at the bold content) will match the following substrings in `!!html!swig?raw=true!./src/tmpl/index.html`:
1. `!` - prefix
2. `./src/tmpl/index.html` - filepath
3. `` - postfix

And the `getFullTemplatePath` function will return the correct full template path `!!html!swig?raw=true!/Absolute/path/to/context/src/tmpl/index.swig`, because of the new regular expression doesn't match `!` and `?` after `?`, so it will not treat the loader query parameters as the postfix, this is the solution.

---

The key source code of the `getFullTemplatePath` function:
```js
// Resolve template path
return template.replace(
  /([!])([^/\\][^!?]+|[^/\\!?])($|\?[^!?\n]+$)/,
  function (match, prefix, filepath, postfix) {
    return prefix + path.resolve(filepath) + postfix;
  });
```

**Comment by jantimon** [comment]
That's quite smart - thanks a lot 👍

**Comment by PeachScript** [comment]
Glad you like it :D

**Comment by PeachScript** [comment]
By the way, when do you plan to release the new version?

**Comment by jantimon** [comment]
Released

**Pull request merged**
