### PR TITLE
Add xhtml option to make link tags self-closing

### PR DESCRIPTION
**Pull request by koenpunt**
Some apps require xhtml tags to be generated (like here https://github.com/webpack/extract-text-webpack-plugin/issues/160)

### CODE REVIEW

**Comment by jantimon** [comment]
Could you please add a note to the readme and a unit test?

**Comment by koenpunt** [comment]
:rocket:

**Comment by jantimon** [comment]
Just thinking - would `selfClosingTags` be better then just `xml` ?

**Comment by koenpunt** [comment]
`xhtml` could more than just closing tags. Maybe eventually there are some required attributes on tags in xhtml, which are not necessary for just html

**Comment by jantimon** [comment]
True but this wouldn't be backwards compatible if we extend xml later on.

**Comment by koenpunt** [comment]
> this wouldn't be backwards compatible

In what way backwards compatible? 

> extend xml later on

You're planning on xml support? How does that work? And in terms of naming, then the package name would be incorrect too I guess.

**Comment by jantimon** [comment]
You said you might want to extend the `xml` feature set for the `xml` option eventually in future.
This would probably break backwards compatibility for people who set `xml` to `true` to get the self closing tags.

**Comment by koenpunt** [comment]
I didn't mention `xml`, only `xhtml`

**Comment by jantimon** [comment]
Sorry for the confusion I meant xhtml.

**Comment by koenpunt** [comment]
Setting `xhtml` to `true` would mean you expect the output to be XHTML compliant, so as long as that's what is does, there won't be any backwards incompatibility further down the line. 
`selfClosingTags` would imply there are other reason than being XHTML compliant for self-closing tags to be present.

**Comment by jantimon** [comment]
Not complete sold but sounds okay

**Comment by koenpunt** [comment]
Cool, could you release a new version of the package? Thanks!

**Pull request merged**
