### PR TITLE
Append new line to inserted tags

### PR DESCRIPTION
**Pull request by L42y**

### CODE REVIEW

**Comment by jantimon** [comment]
Sorry there is no need for those line breaks - you can write a custom template if you need them.

**Comment by dominique-mueller** [comment]
Any specific reason this one got declined? I really feel that line breaks could improve readability of the build output. If needed, the mifier could then go on removing those line-breaks.

**Comment by rshingleton** [comment]
The fact that there are no line breaks is pretty annoying. It's, as dominique-mueller eluded to, like minifying the script/style tags by default, which feels like unexpected behavior.

**Comment by tsurumure** [comment]
eh.. Guys. So do I felling that line breaks is importance. obsessive compulsive disorder :）

**Pull request closed without merging**
