### PR TITLE
add support for managing 'live-reload' url via options

### PR DESCRIPTION
**Pull request by tony-kerz**

### CODE REVIEW

**Comment by tony-kerz** [comment]
hi @jantimon,

this is just to get any early feedback, i'm just in the process of adding a test as well.

best,
tony.

**Comment by jantimon** [comment]
Looks like this conflicts with webpack --inline. See http://stackoverflow.com/questions/31448534/inject-webpack-dev-server-js

**Comment by tony-kerz** [comment]
i haven't been able to get that `--inline` option to work, have you ever used it successfully?

**Comment by jantimon** [comment]
Did you try http://127.0.0.1:8080/webpack-dev-server/

**Pull request closed without merging**
