### PR TITLE
Issue with publicPath and custom template

### PR DESCRIPTION
**Pull request by kos9k**
Hello. Please review this bug fix.

## Reason:

I have custom html template which proceed though my loader like html-loader (this bug was replicated with html-loader also)
my template have this line
```
<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
```
(way with favicon option does not suit me)

href attr converted to [my_dist_directory_with_hash]/images/favicon.ico
my publicPath option for webpack is '/dist/somepath/[hash]/'

after html was emit, attr converted to 

[html_plugin_child_compiler_webpack_publicPath]/images/favicon.ico
html-webpack-plugin

not my publicPath;
I was found only this way for fix this issue)

P.S. Sorry for my English...)))

### CODE REVIEW

**Comment by jantimon** [comment]
Why can't you use the url-loader or file-loader instead?

**Comment by kos9k** [comment]
I have 2 way to compile my project (new with webpack and old) and i need support old compilation procedure. I use file-loader for static files, this described in webpack.config; 

```
{
    test: /\.(ico)$/,
    loader: 'file?name=[path][name].[ext]'
}
```

After emit my files located in my dist directory with hash like
```
dist/[hash]/static_files
mybuild.[hash].js
```

**Comment by jantimon** [comment]
Use the file loader in your html: (won't work with the html-loader)

`<link rel="icon" href="<%= require('./images/favicon.ico') %>" type="image/x-icon" />`

**Comment by kos9k** [comment]
This is not suit for me(((.

**Comment by jantimon** [comment]
Why?

**Comment by kos9k** [comment]
Because i use my own loader (like html-loader) for file.tpl file (like file.html). In this file all static request transforms in require('static/file'), It is the same as you advised me.

**Pull request closed without merging**
