### PR TITLE
Added support for minification using html-minifier

### PR DESCRIPTION
**Pull request by sebastienbarre**
I discovered ```html-webpack-plugin``` today, great tool, thanks.

This PR adds a ```minify``` option (```true``` or an options ```object```), which enables the minification of all resulting HTML files, using [kangax/html-minifier](https://github.com/kangax/html-minifier). This comes handy when you are working on your own (unminified) template file, but want the smallest final output for performance.

Please note that ```html-minifier``` is very conservative by default, as most of [its options](https://github.com/kangax/html-minifier#options-quick-reference) are set to ```false```.
I suggest using these for example:
```
  var HtmlWebpackPlugin = require('html-webpack-plugin');
  var html_webpack_options = {
    template: 'src/assets/index.template.html'
  };
  if (production) {
    html_webpack_options.minify = {
      removeComments: true,
      collapseWhitespace: true,
      conservativeCollapse: true,
      minifyJS: true,
      minifyCSS: true
    };
  }
  config.plugins.push(new HtmlWebpackPlugin(html_webpack_options));
```
Hope this helps.

### CODE REVIEW

**Comment by sebastienbarre** [comment]
Howdy. Anything else you would like me to add or fix there? Thanks.

**Comment by ampedandwired** [comment]
This looks pretty good. Is it perhaps possible to add a test or two and rebase?

**Comment by sebastienbarre** [comment]
@ampedandwired I rebased, but I can't get your tests to run. It assumes ```jshint``` and ```jasmine-node``` are globally installed, which was easy enough to do, but is still failing:
```
> jshint -c .jshintrc *.js spec && jasmine-node --captureExceptions spec

Exception loading: /Volumes/Users/Shared/Src/react/html-webpack-plugin/spec/HtmlWebpackPluginSpec.js
{ [Error: Cannot find module 'tapable'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'tapable'
```
I have ```webpack``` and ```tapable``` globally installed too.

**Comment by jantimon** [comment]
@sebastienbarre I created a new feature branch for this pr:
https://github.com/ampedandwired/html-webpack-plugin/tree/feature/htmlmin

As soon as we got tests it should be ready to merge

**Comment by sebastienbarre** [comment]
@jantimon Thanks. That's what I did, ```npm test```. There are missing ```devDependencies```, but I installed them globally, as mentioned above. It is still failing to run on my Mac as is though.

**Comment by SimenB** [comment]
@sebastienbarre I'm on a Mac, and running `npm i && npm t` works fine. 

```sh
$ npm -g ls --depth 0
/Users/simen/.nvm/versions/node/v0.12.2/lib
├── csslint-stylish@0.0.1 -> /Users/simen/Development/csslint-stylish
├── grunt-contrib-csslint@0.4.0 -> /Users/simen/Development/grunt-contrib-csslint
├── gulp-amdcheck@1.2.5 -> /Users/simen/Development/gulp-amdcheck
├── gulp-csslint@0.1.5 -> /Users/simen/Development/gulp-csslint
├── npm@2.9.0
├── pm2@0.12.13
├── webpack@1.8.11
└── webpack-dev-server@1.8.2
```

**Comment by sebastienbarre** [comment]
Thanks guys. I deleted my ```node_modules``` directory, re-installed, and tests are now passing. Maybe a glitch during a transition to ```iojs```. I'll work on adding a test.

**Comment by SimenB** [comment]
@sebastienbarre You should look at how `html-loader` does it, it picks up whether to minify from the environment if it's not explicit in its options. 
https://github.com/webpack/html-loader/blob/master/index.js#L59

**Pull request closed without merging**
