### PR TITLE
Protocol relative urls support

### PR DESCRIPTION
**Pull request by smolyakoff**
Support for protocol relative urls, for ex. '//domain.com/styles.css'. See issue #205

### CODE REVIEW

**Comment by jantimon** [comment]
Does this really solve your issue?

Extname does not care about the path:

```
> var path = require('path');
> path.extname('##¿¿¿¿\\\//a/b.css')
'.css'
```

**Comment by smolyakoff** [comment]
My case is solved, as chunk name is //domain.com/styles.css 
Do you think there is a better way to extract an extension? '''str.split()''' should also work

**Comment by jantimon** [comment]
Which node version do you use?
`path.extname` does not care about the protocol.

**Comment by smolyakoff** [comment]
```cmd
C:\Windows\System32>node -v
v4.2.1

C:\Windows\System32>node
> require('path').extname('//domain.com/styles.css')
require('path').extname('//domain.com/styles.css')
''
>
```

Returns empty string in this case

**Comment by smolyakoff** [comment]
By the way, I found a workaround to remove publicPath from webpack config when **not** in development. Then it just generates relative urls (without any protocols and domains) and seems to work. 

Can close  the issue, if you think that chunk names with protocol relative urls is not a valid use case for html-webpack-plugin

**Comment by jantimon** [comment]
Ah - windows ;)
Could you please add a unit test for it so it won't be broken again by future changes?

**Comment by jantimon** [comment]
Changed it a little bit and merged it in 2.8.2!
Thamks for your help

**Pull request closed without merging**
