### PR TITLE
Allow custom compile function to be passed

### LINKED ISSUE #38: Using the "Handlebars" (or similar) instead of "Blueimp".
For example, I want to use "partials" in "index.html" — how can I do this?
Thanks.

### PR DESCRIPTION
**Pull request by bebraw**
Closes #38.

### CODE REVIEW

**Comment by bebraw** [comment]
Closing... Just noticed `templateContent`.

**Comment by jantimon** [comment]
Yeah - the readme is out of date. I updated the new one on the 1.4 branch however I am waiting for @ampedandwired to merge it and release the new version to npm

**Comment by bebraw** [comment]
Ok, cool.

**Comment by bebraw** [comment]
After some discussion at Gitter we realized something like this might be needed after all! Even though you can process content through `templateContent` hook it will then get processed by blueimp in any case! So if you output content that blueimp recognizes, you are in trouble.

This PR allows you to work around this issue effectively. It's possible the API will have to change somehow if you want to fix this in a nicer way.

**Comment by jantimon** [comment]
we could move the template compilation in an own file however we would have to add all requested template languages to the package json

**Comment by bebraw** [comment]
Yeah, ideally the choice of templating language would remain in user space. Pulling template libs you don't actually use when you install the plugin would be a big no-no in my books.

**Comment by jantimon** [comment]
I have a huge change which allows to use loaders.
This would also fix this issue.

**Pull request closed without merging**
